apiVersion: v2
name: cardano
description: A Cardano Helm chart for Kubernetes

type: application

version: 0.1.3

appVersion: 1.30.1

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.8.0  # include "common.capabilities.cronjob.apiVersion" macro
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 14.3.3
